# Dependabot with version updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # projects nugets
  # Does not work with native projects
  # Requires a proxy solution
  # - package-ecosystem: "nuget"
  #   directory: "/MeshProc"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
